# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af19713cf734687ccc477c0bac6053edf56a5b4a276adce8e8efa36a2072a8e01298415fb4f4b2fd82d8e74eef01d4313c0b22807a7a21f73f46ab07c5bd8bcd

test:
  secret_key_base: f24eae36169a55c42456547d4987d9348d65dbb1530ab8c203e92a7e5d197d8ef434ff4e8199e8385ab455f3a7a601ec674ed9cb50ad12db742c07d15ea4ce30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
